
package travelgood;

import javax.xml.ws.WebFault;
import travelgoodtypes.ItineraryFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "itineraryFault", targetNamespace = "urn://travelGoodTypes")
public class CancelBookingFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ItineraryFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public CancelBookingFault(String message, ItineraryFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public CancelBookingFault(String message, ItineraryFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: travelgoodtypes.ItineraryFault
     */
    public ItineraryFault getFaultInfo() {
        return faultInfo;
    }

}
