//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.21 at 11:12:20 AM CET 
//


package hotelreservationtypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hotelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hotelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hotelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="address" type="{urn://hotelReservationTypes}addressType"/>
 *         &lt;element name="bookingNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="ccGuaranteeReq" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hotelServiceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hotelType", propOrder = {
    "hotelName",
    "address",
    "bookingNo",
    "price",
    "ccGuaranteeReq",
    "hotelServiceName"
})
public class HotelType {

    @XmlElement(required = true)
    protected String hotelName;
    @XmlElement(required = true)
    protected AddressType address;
    @XmlElement(required = true)
    protected String bookingNo;
    protected float price;
    protected boolean ccGuaranteeReq;
    @XmlElement(required = true)
    protected String hotelServiceName;

    /**
     * Gets the value of the hotelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * Sets the value of the hotelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHotelName(String value) {
        this.hotelName = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the bookingNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingNo() {
        return bookingNo;
    }

    /**
     * Sets the value of the bookingNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingNo(String value) {
        this.bookingNo = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    public float getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    public void setPrice(float value) {
        this.price = value;
    }

    /**
     * Gets the value of the ccGuaranteeReq property.
     * 
     */
    public boolean isCcGuaranteeReq() {
        return ccGuaranteeReq;
    }

    /**
     * Sets the value of the ccGuaranteeReq property.
     * 
     */
    public void setCcGuaranteeReq(boolean value) {
        this.ccGuaranteeReq = value;
    }

    /**
     * Gets the value of the hotelServiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHotelServiceName() {
        return hotelServiceName;
    }

    /**
     * Sets the value of the hotelServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHotelServiceName(String value) {
        this.hotelServiceName = value;
    }

}
