//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.21 at 11:12:20 AM CET 
//


package hotelreservationtypes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hotelreservationtypes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Reset_QNAME = new QName("urn://hotelReservationTypes", "reset");
    private final static QName _HotelCancellationResult_QNAME = new QName("urn://hotelReservationTypes", "hotelCancellationResult");
    private final static QName _HotelCancellationFault_QNAME = new QName("urn://hotelReservationTypes", "hotelCancellationFault");
    private final static QName _HotelBookingResult_QNAME = new QName("urn://hotelReservationTypes", "hotelBookingResult");
    private final static QName _HotelCancellation_QNAME = new QName("urn://hotelReservationTypes", "hotelCancellation");
    private final static QName _HotelBookingFault_QNAME = new QName("urn://hotelReservationTypes", "hotelBookingFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hotelreservationtypes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HotelQuery }
     * 
     */
    public HotelQuery createHotelQuery() {
        return new HotelQuery();
    }

    /**
     * Create an instance of {@link HotelFaultType }
     * 
     */
    public HotelFaultType createHotelFaultType() {
        return new HotelFaultType();
    }

    /**
     * Create an instance of {@link HotelList }
     * 
     */
    public HotelList createHotelList() {
        return new HotelList();
    }

    /**
     * Create an instance of {@link HotelType }
     * 
     */
    public HotelType createHotelType() {
        return new HotelType();
    }

    /**
     * Create an instance of {@link HotelBookingWithCreditCard }
     * 
     */
    public HotelBookingWithCreditCard createHotelBookingWithCreditCard() {
        return new HotelBookingWithCreditCard();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://hotelReservationTypes", name = "reset")
    public JAXBElement<String> createReset(String value) {
        return new JAXBElement<String>(_Reset_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://hotelReservationTypes", name = "hotelCancellationResult")
    public JAXBElement<Boolean> createHotelCancellationResult(Boolean value) {
        return new JAXBElement<Boolean>(_HotelCancellationResult_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HotelFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://hotelReservationTypes", name = "hotelCancellationFault")
    public JAXBElement<HotelFaultType> createHotelCancellationFault(HotelFaultType value) {
        return new JAXBElement<HotelFaultType>(_HotelCancellationFault_QNAME, HotelFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://hotelReservationTypes", name = "hotelBookingResult")
    public JAXBElement<Boolean> createHotelBookingResult(Boolean value) {
        return new JAXBElement<Boolean>(_HotelBookingResult_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://hotelReservationTypes", name = "hotelCancellation")
    public JAXBElement<String> createHotelCancellation(String value) {
        return new JAXBElement<String>(_HotelCancellation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HotelFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://hotelReservationTypes", name = "hotelBookingFault")
    public JAXBElement<HotelFaultType> createHotelBookingFault(HotelFaultType value) {
        return new JAXBElement<HotelFaultType>(_HotelBookingFault_QNAME, HotelFaultType.class, null, value);
    }

}
