//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.21 at 11:12:20 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn://hotelReservationTypes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hotelreservationtypes;
