
package travelgood;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import flightdata.FlightInfoList;
import flightdata.GetFlightQuery;
import hotelreservationtypes.HotelList;
import hotelreservationtypes.HotelQuery;
import travelgoodtypes.Itinerary;
import travelgoodtypes.ItineraryNoWithBookingNo;
import travelgoodtypes.ItineraryNoWithCCInfo;
import travelgoodtypes.OperationSuccessType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "travelGoodPortType", targetNamespace = "urn://travelGood")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    dk.dtu.imm.fastmoney.types.ObjectFactory.class,
    flightdata.ObjectFactory.class,
    hotelreservationtypes.ObjectFactory.class,
    travelgoodtypes.ObjectFactory.class
})
public interface TravelGoodPortType {


    /**
     * 
     * @param hotelQueryRequest
     * @return
     *     returns hotelreservationtypes.HotelList
     */
    @WebMethod
    @WebResult(name = "hotelList", targetNamespace = "urn://hotelReservationTypes", partName = "hotelArray")
    public HotelList listHotelsOperation(
        @WebParam(name = "hotelQuery", targetNamespace = "urn://hotelReservationTypes", partName = "hotelQueryRequest")
        HotelQuery hotelQueryRequest);

    /**
     * 
     * @param flightQuery
     * @return
     *     returns flightdata.FlightInfoList
     */
    @WebMethod
    @WebResult(name = "flightInfoList", targetNamespace = "urn:flightData", partName = "flightList")
    public FlightInfoList listFlightsOperation(
        @WebParam(name = "getFlightQuery", targetNamespace = "urn:flightData", partName = "flightQuery")
        GetFlightQuery flightQuery);

    /**
     * 
     * @param createItineraryReq
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "itineraryNo", targetNamespace = "urn://travelGoodTypes", partName = "itineraryNo")
    public String createItineraryOperation(
        @WebParam(name = "createItineraryRequest", targetNamespace = "urn://travelGoodTypes", partName = "createItineraryReq")
        String createItineraryReq);

    /**
     * 
     * @param addHotelRequest
     * @return
     *     returns travelgoodtypes.OperationSuccessType
     */
    @WebMethod
    @WebResult(name = "operationSuccessResult", targetNamespace = "urn://travelGoodTypes", partName = "success")
    public OperationSuccessType addHotelToItineraryOperation(
        @WebParam(name = "itineraryNoWithBookingNo", targetNamespace = "urn://travelGoodTypes", partName = "addHotelRequest")
        ItineraryNoWithBookingNo addHotelRequest);

    /**
     * 
     * @param addFlightRequest
     * @return
     *     returns travelgoodtypes.OperationSuccessType
     */
    @WebMethod
    @WebResult(name = "operationSuccessResult", targetNamespace = "urn://travelGoodTypes", partName = "success")
    public OperationSuccessType addFlightToItineraryOperation(
        @WebParam(name = "itineraryNoWithBookingNo", targetNamespace = "urn://travelGoodTypes", partName = "addFlightRequest")
        ItineraryNoWithBookingNo addFlightRequest);

    /**
     * 
     * @param itineraryNo
     * @return
     *     returns travelgoodtypes.Itinerary
     */
    @WebMethod
    @WebResult(name = "itinerary", targetNamespace = "urn://travelGoodTypes", partName = "itinerary")
    public Itinerary getItineraryOperation(
        @WebParam(name = "itineraryNo", targetNamespace = "urn://travelGoodTypes", partName = "itineraryNo")
        String itineraryNo);

    /**
     * 
     * @param itineraryNoWithCCInfo
     * @return
     *     returns travelgoodtypes.OperationSuccessType
     * @throws BookItineraryFault
     */
    @WebMethod
    @WebResult(name = "operationSuccessResult", targetNamespace = "urn://travelGoodTypes", partName = "bookItineraryResult")
    public OperationSuccessType bookItineraryOperation(
        @WebParam(name = "itineraryNoWithCCInfo", targetNamespace = "urn://travelGoodTypes", partName = "itineraryNoWithCCInfo")
        ItineraryNoWithCCInfo itineraryNoWithCCInfo)
        throws BookItineraryFault
    ;

    /**
     * 
     * @param itineraryNo
     * @return
     *     returns travelgoodtypes.OperationSuccessType
     * @throws CancelItineraryFault
     */
    @WebMethod
    @WebResult(name = "operationSuccessResult", targetNamespace = "urn://travelGoodTypes", partName = "cancelItineraryResult")
    public OperationSuccessType cancelItineraryOperation(
        @WebParam(name = "itineraryNo", targetNamespace = "urn://travelGoodTypes", partName = "itineraryNo")
        String itineraryNo)
        throws CancelItineraryFault
    ;

    /**
     * 
     * @param itineraryNo
     * @return
     *     returns travelgoodtypes.OperationSuccessType
     * @throws CancelBookingFault
     */
    @WebMethod
    @WebResult(name = "operationSuccessResult", targetNamespace = "urn://travelGoodTypes", partName = "cancelBookingResult")
    public OperationSuccessType cancelBookingOperation(
        @WebParam(name = "itineraryNo", targetNamespace = "urn://travelGoodTypes", partName = "itineraryNo")
        String itineraryNo)
        throws CancelBookingFault
    ;

}
