//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.21 at 11:12:21 AM CET 
//


package flightdata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the flightdata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Reset_QNAME = new QName("urn:flightData", "reset");
    private final static QName _CancelflightResult_QNAME = new QName("urn:flightData", "cancelflightResult");
    private final static QName _BookFlightFailure_QNAME = new QName("urn:flightData", "bookFlightFailure");
    private final static QName _CancelFlightFailure_QNAME = new QName("urn:flightData", "cancelFlightFailure");
    private final static QName _BookflightResult_QNAME = new QName("urn:flightData", "bookflightResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: flightdata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CancelFlightQuery }
     * 
     */
    public CancelFlightQuery createCancelFlightQuery() {
        return new CancelFlightQuery();
    }

    /**
     * Create an instance of {@link GetFlightQuery }
     * 
     */
    public GetFlightQuery createGetFlightQuery() {
        return new GetFlightQuery();
    }

    /**
     * Create an instance of {@link BookFlightQuery }
     * 
     */
    public BookFlightQuery createBookFlightQuery() {
        return new BookFlightQuery();
    }

    /**
     * Create an instance of {@link FlightFaultType }
     * 
     */
    public FlightFaultType createFlightFaultType() {
        return new FlightFaultType();
    }

    /**
     * Create an instance of {@link FlightInfoList }
     * 
     */
    public FlightInfoList createFlightInfoList() {
        return new FlightInfoList();
    }

    /**
     * Create an instance of {@link FlightInfoType }
     * 
     */
    public FlightInfoType createFlightInfoType() {
        return new FlightInfoType();
    }

    /**
     * Create an instance of {@link FlightType }
     * 
     */
    public FlightType createFlightType() {
        return new FlightType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:flightData", name = "reset")
    public JAXBElement<String> createReset(String value) {
        return new JAXBElement<String>(_Reset_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:flightData", name = "cancelflightResult")
    public JAXBElement<Boolean> createCancelflightResult(Boolean value) {
        return new JAXBElement<Boolean>(_CancelflightResult_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlightFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:flightData", name = "bookFlightFailure")
    public JAXBElement<FlightFaultType> createBookFlightFailure(FlightFaultType value) {
        return new JAXBElement<FlightFaultType>(_BookFlightFailure_QNAME, FlightFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlightFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:flightData", name = "cancelFlightFailure")
    public JAXBElement<FlightFaultType> createCancelFlightFailure(FlightFaultType value) {
        return new JAXBElement<FlightFaultType>(_CancelFlightFailure_QNAME, FlightFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:flightData", name = "bookflightResult")
    public JAXBElement<Boolean> createBookflightResult(Boolean value) {
        return new JAXBElement<Boolean>(_BookflightResult_QNAME, Boolean.class, null, value);
    }

}
